# Generated by Django 3.2.6 on 2021-08-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(db_column='g_name', max_length=255)),
                ('g_price', models.DecimalField(db_column='g_price', decimal_places=2, max_digits=10)),
                ('g_picture', models.CharField(db_column='g_picture', max_length=255)),
                ('g_intro', models.CharField(db_column='g_intro', max_length=500)),
                ('g_id', models.IntegerField(db_column='g_id')),
                ('t_id', models.IntegerField(db_column='t_id')),
                ('uptime', models.DateTimeField(auto_now_add=True, db_column='uptime')),
                ('g_total', models.IntegerField(db_column='g_total')),
            ],
            options={
                'db_table': 'tb_goods',
            },
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(db_column='t_id')),
                ('t_status', models.IntegerField(db_column='t_status')),
                ('t_name', models.CharField(db_column='t_name', max_length=255)),
            ],
            options={
                'db_table': 'tb_type',
            },
        ),
    ]
